# Generated by Django 2.1.3 on 2018-11-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_rev_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='book_id_temp',
            field=models.IntegerField(default=0),
        ),
    ]
