# Generated by Django 2.1.3 on 2018-11-04 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_rev_web', '0002_review_book_id_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='book_id_temp',
        ),
    ]
